# Generated by Django 4.2.25 on 2025-10-09 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("NOT_HOMETAX_MEMBER", "홈택스 미가입자"),
                            ("MONTHLY_RENT_REFUND", "월세 환급 대상자"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("test_data", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Test Case",
                "verbose_name_plural": "Test Cases",
                "db_table": "test_cases",
            },
        ),
        migrations.CreateModel(
            name="UserTestCaseAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test_manager.testcase",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Test Case Assignment",
                "verbose_name_plural": "User Test Case Assignments",
                "db_table": "user_test_case_assignments",
            },
        ),
    ]
