[project]
name = "effectivepython"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.1.0",
    "fastapi>=0.116.1",
    "locust>=2.38.0",
    "uvicorn>=0.35.0",
]
